- type: job
  id: StaffOfficer
  name: job-name-staffofficer
  description: job-description-staffofficer
  playTimeTracker: JobStaffOfficer
  requirements:
    - !type:DepartmentTimeRequirement
      department: AlphaGarrison
      time: 0
  startingGear: StaffOfficerGear
  icon: "JobIconStaffOfficer"
  supervisors: job-supervisors-centcom
  canBeAntag: false
  access:
    - Maintenance

- type: startingGear
  id: StaffOfficerGear
  equipment:
    head: ClothingHeadHatWarden
    jumpsuit: ClothingUniformJumpsuitWarden
    back: ClothingBackpackSecurityFilled
    eyes: ClothingEyesGlassesSecurity
    outerClothing: ClothingOuterCoatWarden
    id: WardenPDA
    ears: ClothingHeadsetSecurity
    belt: ClothingBeltSecurityFilled
    pocket1: WeaponPistolMk58Nonlethal
  innerclothingskirt: ClothingUniformJumpskirtWarden
  satchel: ClothingBackpackSatchelSecurityFilled
  duffelbag: ClothingBackpackDuffelSecurityFilled
