- type: job
  id: CharlieEngineer
  name: job-name-charlie-engineer
  description: job-description-charlieengineer
  playTimeTracker: JobCharlieEngineer
  requirements:
    - !type:DepartmentTimeRequirement
      department: CharlieGarrison
      time: 0
    - !type:RoleTimeRequirement
      role: JobAlfaMarine
      time: 0
    - !type:RoleTimeRequirement
      role: JobDeltaMarine
      time: 0
    - !type:RoleTimeRequirement
      role: JobBravoMarine
      time: 0
    - !type:RoleTimeRequirement
      role: JobCharlieMarine
      time: 0
  startingGear: CharlieEngineerGear
  icon: "JobIconCharlieEngineer"
  supervisors: job-supervisors-centcom
  canBeAntag: false
  access:
    - Maintenance

- type: startingGear
  id: CharlieEngineerGear
  equipment:
    head: ClothingHeadHatWarden
    jumpsuit: ClothingUniformJumpsuitWarden
    back: ClothingBackpackSecurityFilled
    eyes: ClothingEyesGlassesSecurity
    outerClothing: ClothingOuterCoatWarden
    id: WardenPDA
    ears: ClothingHeadsetSecurity
    belt: ClothingBeltSecurityFilled
    pocket1: WeaponPistolMk58Nonlethal
  innerclothingskirt: ClothingUniformJumpskirtWarden
  satchel: ClothingBackpackSatchelSecurityFilled
  duffelbag: ClothingBackpackDuffelSecurityFilled
